"""
Core data models for the HFT bot using Pydantic for validation.
"""
from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


class SignalType(str, Enum):
    """Enumeration of possible trading signals."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class TickerData(BaseModel):
    """
    Representation of real-time ticker data.
    """
    symbol: str
    price: float
    volume: float
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    exchange: str = "binance"


class KlineData(BaseModel):
    """
    Representation of candlestick/kline data.
    """
    symbol: str
    open_price: float
    high_price: float
    low_price: float
    close_price: float
    volume: float
    start_time: datetime
    end_time: datetime


class OrderSignal(BaseModel):
    """
    Internal signal generated by the strategy engine.
    """
    symbol: str
    signal: SignalType
    price: float
    confidence: float = Field(ge=0.0, le=1.0)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: Optional[dict] = None


class Position(BaseModel):
    """
    Current holding state for a specific asset.
    """
    symbol: str
    quantity: float
    entry_price: float
    unrealized_pnl: float = 0.0
    timestamp: datetime = Field(default_factory=datetime.utcnow)
